//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEToolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Object.
        /// </summary>
        internal static string ClassType_FloatingObject {
            get {
                return ResourceManager.GetString("ClassType_FloatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Ship.
        /// </summary>
        internal static string ClassType_LargeShip {
            get {
                return ResourceManager.GetString("ClassType_LargeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Ship.
        /// </summary>
        internal static string ClassType_SmallShip {
            get {
                return ResourceManager.GetString("ClassType_SmallShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string ClassType_Station {
            get {
                return ResourceManager.GetString("ClassType_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Ship.
        /// </summary>
        internal static string ImportClassType_LargeShip {
            get {
                return ResourceManager.GetString("ImportClassType_LargeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Ship.
        /// </summary>
        internal static string ImportClassType_SmallShip {
            get {
                return ResourceManager.GetString("ImportClassType_SmallShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.bmp;*.jpg;*.gif;*.png)|*.bmp;*.jpg;*.gif;*.png|All files (*.*)|*.*.
        /// </summary>
        internal static string ImportImagesFilter {
            get {
                return ResourceManager.GetString("ImportImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image to Import.
        /// </summary>
        internal static string ImportImagesTitle {
            get {
                return ResourceManager.GetString("ImportImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Grey.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Black.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut_Black {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Blue.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut_Blue {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Green.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut_Green {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Red.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut_Red {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut White.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut_White {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Yellow.
        /// </summary>
        internal static string MyCharacterModelEnum_Astronaut_Yellow {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string MyCharacterModelEnum_Soldier {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Soldier", resourceCulture);
            }
        }
    }
}
