//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEToolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap asteroid {
            get {
                object obj = ResourceManager.GetObject("asteroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Object.
        /// </summary>
        public static string ClassType_FloatingObject {
            get {
                return ResourceManager.GetString("ClassType_FloatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Ship.
        /// </summary>
        public static string ClassType_LargeShip {
            get {
                return ResourceManager.GetString("ClassType_LargeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Ship.
        /// </summary>
        public static string ClassType_SmallShip {
            get {
                return ResourceManager.GetString("ClassType_SmallShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string ClassType_Station {
            get {
                return ResourceManager.GetString("ClassType_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroid.
        /// </summary>
        public static string ClassType_Voxel {
            get {
                return ResourceManager.GetString("ClassType_Voxel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cube_molecule {
            get {
                object obj = ResourceManager.GetObject("cube_molecule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piloted:	{0}
        ///Damage:	{1}
        ///Speed:	{2:#,##0.000} m/s
        ///Distance:	{3:#,##0.0} m
        ///Scale:	{4} × {5} × {6} blocks
        ///Size:	{7} m × {8} m × {9} m
        ///Mass:	{10:#,##0.00} Kg
        ///Blocks:	{11:#,##0}
        ///Position:	{12}, {13}, {14}
        ///Total time to produce:	{15:dd} days, {15:hh} hours, {15:mm\:ss\.ff}
        ///
        ///Construction Requirements:
        ///Cubes	Count	Mass	Time to Produce
        ///{16}
        ///
        ///Components	Count	Mass	Volume	Time to Produce
        ///{17}
        ///
        ///Ingots	Amount	Mass	Volume	Time to Produce
        ///{18}
        ///
        ///Ore	Amount	Mass	Volume
        ///{19}.
        /// </summary>
        public static string CubeDetail {
            get {
                return ResourceManager.GetString("CubeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_blue {
            get {
                object obj = ResourceManager.GetObject("disk_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_view {
            get {
                object obj = ResourceManager.GetObject("document_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Engineers content file &apos;{0}&apos; could not be loaded, either because it is corrupt, or it is newer than expected..
        /// </summary>
        public static string ExceptionState_CorruptContentFile {
            get {
                return ResourceManager.GetString("ExceptionState_CorruptContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Engineers content file &apos;{0}&apos; could not be loaded, because it may be out of sync with SEToolbox..
        /// </summary>
        public static string ExceptionState_EmptyContentFile {
            get {
                return ResourceManager.GetString("ExceptionState_EmptyContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Engineers content file &apos;{0}&apos; could not be loaded, because it could not be located..
        /// </summary>
        public static string ExceptionState_MissingContentFile {
            get {
                return ResourceManager.GetString("ExceptionState_MissingContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Engineers Application could not be found.
        ///To use the SEToolbox, you must have SpaceEngineers installed on your computer..
        /// </summary>
        public static string ExceptionState_NoApplication {
            get {
                return ResourceManager.GetString("ExceptionState_NoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Engineers Directory &apos;{0}&apos; could not be found.
        ///To use the SEToolbox, you must have SpaceEngineers installed on your computer..
        /// </summary>
        public static string ExceptionState_NoDirectory {
            get {
                return ResourceManager.GetString("ExceptionState_NoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Engineers Game was not detected in Registry.
        ///To use the SEToolbox, you must have SpaceEngineers installed on your computer..
        /// </summary>
        public static string ExceptionState_NoRegistry {
            get {
                return ResourceManager.GetString("ExceptionState_NoRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox Content files (*.htm)|*.htm.
        /// </summary>
        public static string ExportReportFilter {
            get {
                return ResourceManager.GetString("ExportReportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify filename to export &apos;{0}&apos; to.
        /// </summary>
        public static string ExportReportTitle {
            get {
                return ResourceManager.GetString("ExportReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox Content files (*.sbc)|*.sbc|Xml files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string ExportSandboxObjectFilter {
            get {
                return ResourceManager.GetString("ExportSandboxObjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify filename to export &apos;{0}&apos; to.
        /// </summary>
        public static string ExportSandboxObjectTitle {
            get {
                return ResourceManager.GetString("ExportSandboxObjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fit_to_size {
            get {
                object obj = ResourceManager.GetObject("fit_to_size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:		{0}
        ///Distance:		{1:#,##0.0} m
        ///Volume:		{2:#,##0.000} L
        ///Mass:		{3:#,##0.00} Kg
        ///Units:		{4:#,##0}.
        /// </summary>
        public static string FloatingDetail {
            get {
                return ResourceManager.GetString("FloatingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap form_green_view {
            get {
                object obj = ResourceManager.GetObject("form_green_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icecube {
            get {
                object obj = ResourceManager.GetObject("icecube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import1 {
            get {
                object obj = ResourceManager.GetObject("import1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Ship.
        /// </summary>
        public static string ImportClassType_LargeShip {
            get {
                return ResourceManager.GetString("ImportClassType_LargeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Ship.
        /// </summary>
        public static string ImportClassType_SmallShip {
            get {
                return ResourceManager.GetString("ImportClassType_SmallShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.bmp;*.jpg;*.gif;*.png)|*.bmp;*.jpg;*.gif;*.png|All files (*.*)|*.*.
        /// </summary>
        public static string ImportImageFilter {
            get {
                return ResourceManager.GetString("ImportImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image to Import.
        /// </summary>
        public static string ImportImageTitle {
            get {
                return ResourceManager.GetString("ImportImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files|*.3ds;*.lwo;*.obj;*.objx;*.stl;*.off|3D Studio (*.3ds)|*.3ds|Lightwave (*.lwo)|*.lwo|Wavefront (*.obj)|*.obj;*.objx|StereoLithography (*.stl)|*.stl|OFF (*.off)|*.off.
        /// </summary>
        public static string ImportModelFilter {
            get {
                return ResourceManager.GetString("ImportModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model to Import.
        /// </summary>
        public static string ImportModelTitle {
            get {
                return ResourceManager.GetString("ImportModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox Content files (*.sbc)|*.sbc|Xml files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string ImportSandboxObjectFilter {
            get {
                return ResourceManager.GetString("ImportSandboxObjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Sandbox objects to Import.
        /// </summary>
        public static string ImportSandboxObjectTitle {
            get {
                return ResourceManager.GetString("ImportSandboxObjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.vox)|*.vox|All files (*.*)|*.*.
        /// </summary>
        public static string ImportVoxelFilter {
            get {
                return ResourceManager.GetString("ImportVoxelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Asteroid to Import.
        /// </summary>
        public static string ImportVoxelTitle {
            get {
                return ResourceManager.GetString("ImportVoxelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Engineers Application|SpaceEngineers.exe.
        /// </summary>
        public static string LocateApplicationFilter {
            get {
                return ResourceManager.GetString("LocateApplicationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify location of Space Engineers Application.
        /// </summary>
        public static string LocateApplicationTitle {
            get {
                return ResourceManager.GetString("LocateApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap media_stop {
            get {
                object obj = ResourceManager.GetObject("media_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap message_edit {
            get {
                object obj = ResourceManager.GetObject("message_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick Shell.
        /// </summary>
        public static string ModelTraceVoxel_Thick {
            get {
                return ResourceManager.GetString("ModelTraceVoxel_Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick Shell with Smoothing.
        /// </summary>
        public static string ModelTraceVoxel_ThickSmoothed {
            get {
                return ResourceManager.GetString("ModelTraceVoxel_ThickSmoothed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin Shell.
        /// </summary>
        public static string ModelTraceVoxel_Thin {
            get {
                return ResourceManager.GetString("ModelTraceVoxel_Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin Shell with Smoothing.
        /// </summary>
        public static string ModelTraceVoxel_ThinSmoothed {
            get {
                return ResourceManager.GetString("ModelTraceVoxel_ThinSmoothed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Grey.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Black.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut_Black {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Blue.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut_Blue {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Green.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut_Green {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Red.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut_Red {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut White.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut_White {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronaut Yellow.
        /// </summary>
        public static string MyCharacterModelEnum_Astronaut_Yellow {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Astronaut_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        public static string MyCharacterModelEnum_Soldier {
            get {
                return ResourceManager.GetString("MyCharacterModelEnum_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap navigate_left2 {
            get {
                object obj = ResourceManager.GetObject("navigate_left2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap navigate_right2 {
            get {
                object obj = ResourceManager.GetObject("navigate_right2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap package_add {
            get {
                object obj = ResourceManager.GetObject("package_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap photo_scenery {
            get {
                object obj = ResourceManager.GetObject("photo_scenery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap screwdriver {
            get {
                object obj = ResourceManager.GetObject("screwdriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SECubes16 {
            get {
                object obj = ResourceManager.GetObject("SECubes16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server_to_client {
            get {
                object obj = ResourceManager.GetObject("server_to_client", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shield {
            get {
                object obj = ResourceManager.GetObject("shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sort_descending {
            get {
                object obj = ResourceManager.GetObject("sort_descending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpaceEngineers16 {
            get {
                object obj = ResourceManager.GetObject("SpaceEngineers16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap speedometer {
            get {
                object obj = ResourceManager.GetObject("speedometer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Toolbox {
            get {
                object obj = ResourceManager.GetObject("Toolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ToolboxSplash {
            get {
                object obj = ResourceManager.GetObject("ToolboxSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap transform {
            get {
                object obj = ResourceManager.GetObject("transform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename:	{0}
        ///Bounding Size:	{1} × {2} × {3} blocks
        ///Size:	{4} m × {5} m × {6} m
        ///Volume:	{7:#,##0.00} m³
        ///VoxCells:	{8:#,##0}
        ///Distance:	{9:#,##0.0} m
        ///Position:	{10}, {11}, {12}
        ///
        ///Material	Mass	Percent
        ///{13}.
        /// </summary>
        public static string VoxelDetail {
            get {
                return ResourceManager.GetString("VoxelDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning32 {
            get {
                object obj = ResourceManager.GetObject("warning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap workshop16 {
            get {
                object obj = ResourceManager.GetObject("workshop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wrench {
            get {
                object obj = ResourceManager.GetObject("wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
