namespace SEToolbox.ViewModels
{
    using System.ComponentModel;
    using System.Windows;
    using System.Windows.Input;
    using SEToolbox.Models;
    using SEToolbox.Services;

    public class StructurePlanetViewModel : StructureBaseViewModel<StructurePlanetModel>
    {
        #region ctor

        public StructurePlanetViewModel(BaseViewModel parentViewModel, StructurePlanetModel dataModel)
            : base(parentViewModel, dataModel)
        {
            DataModel.PropertyChanged += delegate (object sender, PropertyChangedEventArgs e)
            {
                // Will bubble property change events from the Model to the ViewModel.
                OnPropertyChanged(e.PropertyName);
            };
        }

        #endregion

        #region command properties

        public ICommand CopyDetailCommand
        {
            get { return new DelegateCommand(CopyDetailExecuted, CopyDetailCanExecute); }
        }

        #endregion

        #region Properties

        protected new StructurePlanetModel DataModel
        {
            get { return base.DataModel as StructurePlanetModel; }
        }

        public string Name
        {
            get { return DataModel.Name; }
            set { DataModel.Name = value; }
        }

        public BindableVector3DModel Center
        {
            get { return new BindableVector3DModel(DataModel.Center); }
            set { DataModel.Center = value.ToVector3(); }
        }

        public float Radius
        {
            get { return DataModel.Radius; }
            set { DataModel.Radius = value; }
        }

        public bool HasAtmosphere
        {
            get { return DataModel.HasAtmosphere; }
            set { DataModel.HasAtmosphere = value; }
        }

        public float AtmosphereRadius
        {
            get { return DataModel.AtmosphereRadius; }
            set { DataModel.AtmosphereRadius = value; }
        }

        public float MinimumSurfaceRadius
        {
            get { return DataModel.MinimumSurfaceRadius; }
            set { DataModel.MinimumSurfaceRadius = value; }
        }

        public float MaximumHillRadius
        {
            get { return DataModel.MaximumHillRadius; }
            set { DataModel.MaximumHillRadius = value; }
        }

        public float GravityFalloff
        {
            get { return DataModel.GravityFalloff; }
            set { DataModel.GravityFalloff = value; }
        }

        public float SurfaceGravity
        {
            get { return DataModel.SurfaceGravity; }
            set { DataModel.SurfaceGravity = value; }
        }

        public bool SpawnsFlora
        {
            get { return DataModel.SpawnsFlora; }
            set { DataModel.SpawnsFlora = value; }
        }

        public bool ShowGPS
        {
            get { return DataModel.ShowGPS; }
            set { DataModel.ShowGPS = value; }
        }

        public string PlanetGenerator
        {
            get { return DataModel.PlanetGenerator; }
            set { DataModel.PlanetGenerator = value; }
        }

        #endregion

        #region methods

        public bool CopyDetailCanExecute()
        {
            return true;
        }

        public void CopyDetailExecuted()
        {
            var detail = string.Format(Properties.Resources.CtlPlanetDetail,
                Name,
                Center.X, Center.Y, Center.Z,
                PlayerDistance,
                PositionAndOrientation.Value.Position.X, PositionAndOrientation.Value.Position.Y, PositionAndOrientation.Value.Position.Z,
                Radius,
                HasAtmosphere,
                AtmosphereRadius,
                MinimumSurfaceRadius,
                MaximumHillRadius,
                GravityFalloff,
                SurfaceGravity,
                SpawnsFlora,
                ShowGPS,
                PlanetGenerator);

            try
            {
                Clipboard.Clear();
                Clipboard.SetText(detail);
            }
            catch
            {
                // Ignore exception which may be generated by a Remote desktop session where Clipboard access has not been granted.
            }
        }

        #endregion
    }
}
